version: '3'
services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx-1_28
    restart: always
    ports:
#      - 80:80
      - 8080:8080
    environment:
      TZ: 'Asia/Shanghai'
    logging:
      options:
        max-size: "10m"
    volumes:
      - ./logs:/var/log/nginx
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/.htpasswd:/etc/nginx/.htpasswd # 默认账号密码 skywalking:skywalking