version: '2'
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: cloudflare_tunnel
    command: "tunnel --no-autoupdate run --token ${TOKEN}"
